[workspace]
authors = ["issanym <jacinthenym@proton.me>"]
channels = ["robostack-humble", "conda-forge"]
name = "bullseye"
platforms = ["linux-64","win-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
build = "colcon build"
follow = "ros2 run follower bullseye --ros-args -p camera_index:=0 -p show_debug_window:=true" # camera index to 0 for webcam

[activation]
scripts = ["install/setup.sh", "install/setup.bat"]

[target.unix.activation.env] # linux only parameters
QT_QPA_PLATFORM="xcb"
GDK_BACKEND="x11"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
opencv = ">=4.13.0,<5"
colcon-common-extensions = ">=0.3.0,<0.4"
numpy = ">=2.5.1,<3"
